# Generated by Django 3.2.13 on 2024-07-29 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_employee_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.module')),
                ('module_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.modulefield')),
            ],
            options={
                'db_table': 'content',
            },
        ),
    ]
